# -*- coding: utf-8 -*-
"""Day1_DA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eA5XJ1bLVVIDHgPuCnPQQiEIURoqGsDO

Types of Python operator used in DA
- Assignment
- Arithmetic
- Logical
- Bitwise (Won't Use)
- Identity
- Membership
- Comparision
"""

a=1
print(id(a))

b=1
print(id(b))

a=300
print(id(a))

b=300
print(id(b))

a = int(input('Enter the no. : '))
b = int(input('Enter the no. : '))
c=a+b
print(c)

"""# Arethimatic Operators
+
-
/
//
%

# Assignment Operator
"""

a=10
a+=10
print(a)

a=10
a//=10
print(a)

a=10
a/=10
print(a)

"""#Comparison Operator"""

a=10
b=20
a==b

"""#Logical Operator

#not
"""

not(-1)

not(1)

not(True)

not(False)

not(100)

not(0)

"""#and"""

True and True

False and True

True and False

False and False

1 and 1

1 and 0

0 and 1

0 and 0

10 and 20

20 and 10

10 and 0

0 and 20

"""#or"""

True or True

False or False

True or False

False or True

10 or 20

20 or 10

1 or 0

0 or 1

1 or 1

0 or 1

"""#Membership Operator
in or not in
"""

a = "This is my python class"
"this" in a

a = "This is my python class"
"This" in a

a = "This is my python class"
"i" in a

a = "This is my python class"
"is i" in a

a = "This is my python class"
"is i"  not in a

"""#Identity Operator
is and is not
"""

a=10
b=20
a is b

a is not b

a="this is my python class"
"this" is a

a = "this is my python class"
"this is my python class" is a

"""#**Data Types**
# Numeric
- int
- float
- complex

#sequence data type
- list
- tuple
- dict
- set
-string

#Boolean
- True
- False
"""